name: Ubuntu testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build 
        run: |
            apt-get install libboost-all-dev
            bazel build ...
      - name: test
        run: |
            bazel build ...

